### ISSUE TITLE
Does it not work with yaml?

### ISSUE THREAD

**Issue by smff** [reeli/swagger-faker#10]
?

**Comment by reeli** [comment]
It only allow json format as of now, but you can convert yaml to json format first, the pull request is welcomed. @smff

**Comment by smff** [comment]
I'm sorry, but it hard for me(forks / access, etc) to open PR, so I made a patch for you )
[0001-smff-added-yaml-format.patch](https://github.com/reeli/swagger-faker/files/11528434/0001-smff-added-yaml-format.patch)

**Comment by reeli** [comment]
Please install the latest version 3.3.0, yaml is supported in this version @smff
