### ISSUE TITLE
Error while trying the example

### ISSUE THREAD

**Issue by migmaarten** [reeli/swagger-faker#5]
I have tried to run the example code on win10 in the Git-bash
I got the following error:

$ npm start

> @reeli/swagger-faker-examples@1.0.0 start
> rm -rf mock-server && swagger-faker gen && swagger-faker run

Generate config to mock-server folder successfully!

  \{^_^}/ hi!

  Loading mock-server/db.js
  Loading mock-server/middlewares/*.js
Error: Cannot find module 'F:\Sources\IdolSecurity\swagger-faker-examples\mock-server\middlewares\*.js'
Require stack:
- F:\Sources\IdolSecurity\swagger-faker-examples\node_modules\json-server\lib\cli\run.js
- F:\Sources\IdolSecurity\swagger-faker-examples\node_modules\json-server\lib\cli\index.js
- F:\Sources\IdolSecurity\swagger-faker-examples\node_modules\json-server\lib\cli\bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at F:\Sources\IdolSecurity\swagger-faker-examples\node_modules\json-server\lib\cli\run.js:127:18
    at Array.map (<anonymous>)
    at F:\Sources\IdolSecurity\swagger-faker-examples\node_modules\json-server\lib\cli\run.js:125:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'F:\\Sources\\IdolSecurity\\swagger-faker-examples\\node_modules\\json-server\\lib\\cli\\run.js',
    'F:\\Sources\\IdolSecurity\\swagger-faker-examples\\node_modules\\json-server\\lib\\cli\\index.js',
    'F:\\Sources\\IdolSecurity\\swagger-faker-examples\\node_modules\\json-server\\lib\\cli\\bin.js'
  ]
}

**Comment by reeli** [comment]
@migmaarten 
Just fixed the issue and upgrade the swagger-faker to `v3.1.0`, please try again by pull the latest swagger-faker-examples or reclone it. As I don't have the windows machine to test, please let me know if it's not work.

Thanks a lot!
