### ISSUE TITLE
Can't run mock service

### ISSUE THREAD

**Issue by Qishierhao** [reeli/swagger-faker#7]
**description**
install the template，and copy the JSON to swagger.json，runstart and fail
ps：becuase windows didnot support rm-rf，installed rimraf-3.0.2

**error**
(node:34700) UnhandledPromiseRejectionWarning: S2OError: (Patchable) parameter.type is mandatory for non-body parameters
TypeError: app.use() requires a middleware function

**image**
![image](https://user-images.githubusercontent.com/43943555/161362813-64e16b0b-b073-4a3a-9921-ef8d4f4c3a4e.png)

**Log：**
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start',
1 verbose cli   '--scripts-prepend-node-path=auto'
1 verbose cli ]
2 info using npm@6.14.16
3 info using node@v14.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @reeli/swagger-faker-examples@1.0.0~prestart: @reeli/swagger-faker-examples@1.0.0
6 info lifecycle @reeli/swagger-faker-examples@1.0.0~start: @reeli/swagger-faker-examples@1.0.0
7 verbose lifecycle @reeli/swagger-faker-examples@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle @reeli/swagger-faker-examples@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\Projects\swagger-faker-examples\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Program Files\Git\cmd;%adb%;C:\Users\EnochJiang\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\EnochJiang\AppData\Local\Programs\Python\Python310\;C:\Users\EnochJiang\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\Program Files\JetBrains\WebStorm 2021.3.2\bin;;C:\Users\EnochJiang\AppData\Roaming\npm;C:\Users\EnochJiang\AppData\Local\Yarn\bin
9 verbose lifecycle @reeli/swagger-faker-examples@1.0.0~start: CWD: D:\Projects\swagger-faker-examples
10 silly lifecycle @reeli/swagger-faker-examples@1.0.0~start: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'rimraf mock-server && swagger-faker gen && swagger-faker run'
10 silly lifecycle ]
11 silly lifecycle @reeli/swagger-faker-examples@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle @reeli/swagger-faker-examples@1.0.0~start: Failed to exec start script
13 verbose stack Error: @reeli/swagger-faker-examples@1.0.0 start: `rimraf mock-server && swagger-faker gen && swagger-faker run`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1058:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
14 verbose pkgid @reeli/swagger-faker-examples@1.0.0
15 verbose cwd D:\Projects\swagger-faker-examples
16 verbose Windows_NT 10.0.22000
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start" "--scripts-prepend-node-path=auto"
18 verbose node v14.19.0
19 verbose npm  v6.14.16
20 error code ELIFECYCLE
21 error errno 1
22 error @reeli/swagger-faker-examples@1.0.0 start: `rimraf mock-server && swagger-faker gen && swagger-faker run`
22 error Exit status 1
23 error Failed at the @reeli/swagger-faker-examples@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by reeli** [comment]
Just fixed it, you can pull the latest code, or you just remove this command `rm -rf mock-server` in your local, as a demo we can keep the `mock-server` folder, after that you'll get the correct response.
